### PR TITLE
Include citations in preview popups

### PR DESCRIPTION
**Pull request by tnajdek**
Include citations in preview popups #30

screen shot 2016-08-31 at 18 07 12

### CODE REVIEW

**Comment by rmzelle** [comment]
Has this gone live yet? I don't see the citations yet in the popups.

**Comment by dstillman** [comment]
Sorry, hadn't gone live on the production site, only dev. Up now. (And https://github.com/zotero/styles-repo/issues/20#issuecomment-218754464 is more of a problem now. Maybe @tnajdek has an easy fix for that.)

**Comment by dstillman** [comment]
I also think we can style this better. Maybe just "Citation:" and "Bibliography:" headers instead of the gray box?

**Comment by rmzelle** [comment]
(I now get "An internal server error occurred. Please try again later." for the styles page)

**Comment by dstillman** [comment]
Still? The apex URL (https://zotero.org without www) was down momentarily, but should be back now.

**Comment by rmzelle** [comment]
It's back. (and yes, my visit was to "zotero.org/styles")

**Comment by rmzelle** [comment]
For non-"note" styles, for which the citations are almost always quite short, maybe citations and bibliography could be shown side-by-side instead of below each other? Would save some vertical space.

And agree that labels would be clearer than the current shading.

**Pull request closed without merging**
