### PR TITLE
Update previews.json

### LINKED ISSUE #12: Periods missing from Journal Abbreviations in Preview
For styles like elsevier-harvard, journal abbreviations should include periods, and they do in the underlying JSON data, but not in the generated previews. Styles display correctly locally.

### PR DESCRIPTION
**Pull request by rmzelle**
Should fix #12

### CODE REVIEW

**Comment by rmzelle** [comment]
@dstillman, has this been pushed to https://www.zotero.org/styles ?

**Comment by rmzelle** [comment]
Or are previews only regenerated for individual styles, not for the entire repo, when styles are added/updated? That could also explain why I still don't see this change reflected in the style previews.

**Comment by dstillman** [comment]
Sorry, repo that does the preview generation wasn't updated. Should be fixed now (though the old version might be cached for you locally).

**Comment by rmzelle** [comment]
All good now! Thanks. (cc @adam3smith)

**Pull request merged**
